### ISSUE TITLE
updating  chernarus.xml with the 1.08 version please :)

### ISSUE THREAD

**Issue by YakovSemechki** [BohemiaInteractive/DayZ-Central-Economy#2]
hello so yes i d like to access the 1.08 chernarus.xml and also maybe if you could rework a bit the objects spawning 50m from where they re suppose to spawn

**Comment by Arkensor** [comment]
The files were updated now

**Comment by YakovSemechki** [comment]
Thanks for the feedback sir :)Envoyé depuis mon téléphone Huawei-------- Message original --------De : Arkensor <notifications@github.com>Date : mer. 8 juill. 2020 08:50À : BohemiaInteractive/DayZ-Central-Economy <DayZ-Central-Economy@noreply.github.com>Cc : YakovSemechki <tinarimassimo@gmail.com>, Author <author@noreply.github.com>Objet : Re: [BohemiaInteractive/DayZ-Central-Economy] updating  chernarus.xml with the 1.08 version please :) (#2)
The files were updated now
